language: generic 
sudo: required

services:
 - docker

before_install:
 - docker build -t oluwashola/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true oluwashola/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-us-east-2-934255252010"
 bucket_path: "docker-react"
 on:
  branch: main
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: "$AWS_SECRET_KEY"



 
